### ISSUE TITLE
Make the GeneratePersonName function output different things

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/naminglanguage#12]
The GeneratePersonName function should take a new argument that allows for different kinds of output. The following should be options:

* First name only
* Last name only
* First and last name
* First and last name, followed by meaning (this is the current output)

**Comment by jeanmorais** [comment]
@BenOvermyer I think I can do that. Do you prefer multiple returns, or a string argument using switch?

**Comment by BenOvermyer** [comment]
I'd prefer a string argument using switch.

**Comment by jeanmorais** [comment]
@BenOvermyer I'll do this. Thanks.

**Comment by nbazzeghin** [comment]
PR Submitted: https://github.com/ironarachne/naminglanguage/pull/14
