### ISSUE TITLE
Add option for "namegen" command to output JSON results

### ISSUE THREAD

**Issue by BenOvermyer** [ironarachne/naminglanguage#3]
The output should be an array of objects, with each object being a set of key-value pairs.

People should include first name, last name, first name meaning, and last name meaning as separate items.

Places should include name and meaning as separate items.

**Comment by IngCr3at1on** [comment]
@BenOvermyer mind if I grab this one?

**Comment by BenOvermyer** [comment]
@IngCr3at1on Go for it.
